#! /bin/sh
#  Copyright (C) 2016 Hewlett Packard Enterprise Development LP
#



# Function : copy_to_tmp
#
# Description : This function copies files to /tmp .
#               docker uses host machines kernel and only /tmp is shared across
#               vm and docker. Host machine kernel invokes docker shell script
#               to write core file .
#
function copy_to_tmp()
{
    cp -f /etc/os-release        /tmp
    cp -f /sbin/ops_cdm.sh       /tmp
    cp -f /etc/ops_corefile.conf /tmp
}

###### Entry routine ######
copy_to_tmp
exit $?
######  ######
